version: '3'

services:
  influx:
    image: solderra/armhf-influxdb
    ports:
      - 0.0.0.0:8083:8083
      - 0.0.0.0:8086:8086
    networks:
      - piarmy
    volumes:
      - influx:/var/lib/influxdb
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  grafana:
    image: braingamer/grafana-arm
    ports:
      - 0.0.0.0:8080:3000
    networks:
      - piarmy
    volumes:
      - grafana:/var/lib/grafana
    depends_on:
      - influx
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  cadvisor:
    image: braingamer/cadvisor-arm:latest
    networks:
      - piarmy
    hostname: '{{.Node.ID}}'
    command: -logtostderr -docker_only -storage_driver=influxdb -storage_driver_db=cadvisor -storage_driver_host=influx:8086
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
      - influx
    deploy:
      mode: global

volumes:
  influx:
    driver: local
  grafana:
    driver: local

networks:  
  piarmy:
    external: true
